---
- name: 'Add the virtualbox apt signing key'
  sudo: yes
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '98AB5139'
    state: present

- name: 'Add the Virtualbox ubuntu repo'
  sudo: yes
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: yes

- name: 'Install Virtualbox'
  sudo: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'virtualbox-5.0'
    - 'dkms'

