---
- name: 'Install NTP daemon'
  sudo: true
  apt:
    pkg: 'ntp'
    state: present

- name: 'Ensure the NTP daemon autostarts'
  sudo: true
  service:
    name: 'ntp'
    enabled: yes
    state: started

- name: 'Setup NTP daemon config'
  sudo: true
  template:
    src: 'ntpd.conf.j2'
    dest: '/etc/ntp.conf'
  notify: 'Restart NTP daemon'
