---
- name: 'Install apt-transport-https'
  sudo: 'yes'
  apt:
    name: 'apt-transport-https'

- name: 'Add the docker apt signing key'
  sudo: 'yes'
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '58118E89F3A912897C070ADBF76221572C52609D'

- name: 'Add the official docker repo'
  sudo: 'yes'
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    state: 'present'
  notify: 'Perform an apt-get update'

- meta: flush_handlers

- name: 'Install docker'
  sudo: 'yes'
  apt:
    name: 'docker-engine'
    state: latest

- name: 'Ensure that the docker service is running'
  sudo: true
  service:
    name: 'docker'
    state: started
    enabled: yes

- name: 'Add marvin to the docker group'
  sudo: yes
  user:
    name: 'marvin'
    groups: 'docker'
    append: yes

- name: 'Set the docker apparmor profile to complain mode'
  sudo: yes
  file:
    src: '/etc/apparmor.d/docker'
    dest: '/etc/apparmor.d/force-complain/docker'
    state: 'link'
  notify: 'Reload apparmor'
