---
- name: 'Install apt-transport-https'
  sudo: 'yes'
  apt:
    name: 'apt-transport-https'

- name: 'Add the docker apt signing key'
  sudo: 'yes'
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '36A1D7869245C8950F966E92D8576A8BA88D21E9'

- name: 'Add the docker.io repo'
  sudo: 'yes'
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
    state: 'present'
  notify: 'Perform an apt-get update'

- meta: flush_handlers

- name: 'Install docker'
  sudo: 'yes'
  apt:
    name: 'lxc-docker'

- name: 'Ensure that the docker service is running'
  sudo: true
  service:
    name: 'docker'
    state: started
    enabled: yes

- name: 'Add marvin to the docker group'
  sudo: yes
  user:
    name: 'marvin'
    groups: 'docker'
    append: yes

- name: 'Set the docker apparmor profile to complain mode'
  sudo: true
  lineinfile:
    dest: '/etc/rc.local'
    state: present
    insertbefore: "^exit 0"
    line: 'aa-complain /etc/apparmor.d/docker'
    regexp: '^aa-complain /etc/apparmor.d/docker'
    owner: 'root'
    group: 'root'
    mode: '0755'
